### ISSUE TITLE
Problem running the debugger

### ISSUE THREAD

**Issue by mmajkafmp** [enricop89/aws-lambda-typescript-debug#5]
Hi there, thanks for posting your solution here. I'm having trouble setting up the debugger locally so checked out your repository and got the exact same problem:

```
Debugger attached.
Waiting for the debugger to disconnect...
c:\GitHub\aws-lambda-typescript-debug\node_modules\.bin\sls:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Process exited with code 1
```

Not sure what's wrong there.

My Node.js version: v12.18.1

**UPDATE 1**: I just realised I'm running in Windows 10 and trying to run the `sls` bash script. Will try in Linux but the `launch.json` configuration might need to be updated for Win10.

**UPDATE 2**: works in Linux so it's just Win10 that needs some special treatment.

**Comment by DiegoFleitas** [comment]
I'm on W10, using the .cmd worked for me

```
"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/sls.cmd",
"runtimeArgs": ["invoke", "local", "-f", "pollTwitterFeed", "--data", "{}"],
```

**Comment by pisrael** [comment]
@DiegoFleitas fix worked perfectly for me on Windows 11 replacing "program" and "args" configurations
